# Generated by Django 4.2 on 2023-05-03 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('temporary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary',
            name='date_add',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
