# Generated by Django 4.2 on 2023-05-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporary', '0002_alter_temporary_date_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary',
            name='night',
            field=models.BooleanField(default=False),
        ),
    ]
