# Generated by Django 4.2 on 2023-05-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporary', '0004_alter_temporary_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary',
            name='day',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Восересенье', 'Восересенье')], max_length=20),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='shift_type',
            field=models.CharField(choices=[('FT', 'FT'), ('Первая смена', 'Первая смена'), ('Вторая смена', 'Вторая смена'), ('Выходной', 'Выходной'), ('Другое', 'Другое')], max_length=30),
        ),
    ]
